<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="hp" ignored="0" name="Testrunner1" tests="1" failures="1" timestamp="13 Oct 2022 14:58:30 GMT" time="74.928" errors="0">
  <testcase name="createOrganization" time="27.878" classname="comm.crm.Organization.Vtigerrr">
    <failure type="java.lang.AssertionError" message="expected [false] but found [true]">
      <![CDATA[java.lang.AssertionError: expected [false] but found [true]
	at comm.crm.Organization.Vtigerrr.createOrganization(Vtigerrr.java:65)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
... Removed 22 stack frames]]>
    </failure>
  </testcase> <!-- createOrganization -->
</testsuite> <!-- Testrunner1 -->
